# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:

  my-home-status:
    # image: ianstorm/my-home-status:latest
    build: .
    env_file: ./credentials/status.env
    restart: always
    ports:
      - 8080:8080
