FROM twinproduction/gatus:v5.16.0

ENV GATUS_ALERTING_EMAIL_FROM=
ENV GATUS_ALERTING_EMAIL_HOST=
ENV GATUS_ALERTING_EMAIL_PASSWORD=
ENV GATUS_ALERTING_EMAIL_TO=
ENV GATUS_ALERTING_EMAIL_USERNAME=

COPY ./alpine-root/config/ /config/
