FROM node:22.22.0-alpine AS config-builder

COPY ./ /workspace/

RUN cd /workspace/ \
	&& npm clean-install \
	&& npm run build \
	&& npm start

#
# ⬇️ main stage
#
FROM twinproduction/gatus:v5.35.0

ENV DOMAINS_DE_MIGADUVERIFY=
ENV DOMAINS_DE_NAME=
ENV DOMAINS_DE_SUBDOMAINS_CH_MIGADUVERIFY=
ENV DOMAINS_DE_SUBDOMAINS_CH_NAME=
ENV DOMAINS_DE_SUBDOMAINS_NC_NAME=
ENV DOMAINS_DE_SUBDOMAINS_NC_STORAGESHAREID=
ENV DOMAINS_DE_SUBDOMAINS_NR_MIGADUVERIFY=
ENV DOMAINS_DE_SUBDOMAINS_NR_NAME=
ENV DOMAINS_DE_SUBDOMAINS_SA_MIGADUVERIFY=
ENV DOMAINS_DE_SUBDOMAINS_SA_NAME=
ENV DOMAINS_ME_NAME=
ENV DOMAINS_ME_SUBDOMAINS_CH_MIGADUVERIFY=
ENV DOMAINS_ME_SUBDOMAINS_CH_NAME=
ENV DOMAINS_ME_SUBDOMAINS_FAM_MIGADUVERIFY=
ENV DOMAINS_ME_SUBDOMAINS_FAM_NAME=
ENV DOMAINS_ME_SUBDOMAINS_SA_MIGADUVERIFY=
ENV DOMAINS_ME_SUBDOMAINS_SA_NAME=
ENV GATUS_ALERTING_EMAIL_FROM=
ENV GATUS_ALERTING_EMAIL_HOST=
ENV GATUS_ALERTING_EMAIL_PASSWORD=
ENV GATUS_ALERTING_EMAIL_PORT=
ENV GATUS_ALERTING_EMAIL_TO=
ENV GATUS_ALERTING_EMAIL_USERNAME=

ENV GATUS_LOG_LEVEL=DEBUG

COPY --from=config-builder /workspace/alpine-root/config/ /config/
