endpoints:
  - name: pihole
    group: my-home-dns
    url: "http://my-home-dns/admin"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] <= 299"
    alerts:
      - type: email

  - name: mqtt
    group: my-smart-home
    url: "http://my-smart-home:8083"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] <= 299"
    alerts:
      - type: email

  - name: node-red
    group: my-smart-home
    url: "http://my-smart-home:1880/ui"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] <= 299"
    alerts:
      - type: email

  - name: zigbee2mqtt
    group: my-smart-home
    url: "http://my-smart-home:8099"
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] <= 299"
    alerts:
      - type: email


alerting:
  email:
    from: ${GATUS_ALERTING_EMAIL_FROM}
    host: ${GATUS_ALERTING_EMAIL_HOST}
    password: ${GATUS_ALERTING_EMAIL_PASSWORD}
    port: 587
    to: ${GATUS_ALERTING_EMAIL_TO}
    username: ${GATUS_ALERTING_EMAIL_USERNAME}


maintenance:
  start: 02:45
  duration: 1h
  timezone: "Europe/Berlin"
  every: [] # daily


storage:
  type: memory
